import React, { useState } from 'react'
import { usarDatos } from '../datos.jsx'
import { puedeEditarRol } from '../roles.js'
import { moneda } from '../formato.js'
import { mapaConfig, configNum } from '../calc.js'
import { ARTISTAS_SONORA, leerRecintos, calcularRecinto, consolidarRecintos } from '../recintos.js'
import { BASE } from '../config.js'
import './recintos.css'
const dinero=v=>Number.isFinite(v)?moneda(v):'Por definir'
const campos=[['capacidad','Capacidad / unidades'],['periodos','Periodos por año'],['ocupacion','Ocupación (%)'],['precio','Precio unitario (MXN)'],['retencion','Ingreso retenido (%)'],['extra','Complemento neto por unidad (MXN)'],['variable','Costo variable (%)'],['fijos','Costo fijo anual (MXN)'],['renta','Renta imputada anual (MXN)'],['regalias','Regalías brutas anuales (MXN)'],['split','Participación del distrito (%)'],['costoRegalias','Gestión de regalías (%)'],['area','Área asignada (m²)']]
export function RecintosVista({datos,sesion,modo,editarFila,guardados={},reintentarGuardado,espacioId}) {
  const leidos=leerRecintos(datos)
  const validos=espacioId?leidos.validos.filter(x=>x.fila.espacio_id===espacioId):leidos.validos
  const errores=leidos.errores
  const [seleccion,setSeleccion]=useState(espacioId||validos[0]?.fila.espacio_id)
  const [escenario,setEscenario]=useState('base')
  const [cambios,setCambios]=useState({})
  const editable=modo!=='demo'&&puedeEditarRol(sesion?.rol)
  const planes=validos.map(x=>cambios[x.fila.id]||x.plan)
  const acciones=configNum(mapaConfig(datos?.Config),'acciones_emitidas',0)
  const total=errores.length ? {errores:['Hay borradores ilegibles: no se consolida un total parcial.']} : consolidarRecintos(planes,acciones,escenario)
  const indice=validos.findIndex(x=>x.fila.espacio_id===seleccion)
  const idx=indice<0?0:indice, actual=validos[idx], plan=planes[idx]
  const espacio=datos?.Espacios?.find(e=>e.id===actual?.fila.espacio_id)
  const resultado=plan?calcularRecinto(plan,escenario):null
  function cambiar(planNuevo){setCambios(x=>({...x,[actual.fila.id]:planNuevo}));if(editable)editarFila('Conocimientos',actual.fila.id,{texto:JSON.stringify(planNuevo),estado:'nos falta'})}
  function unidad(i,clave,valor){cambiar({...plan,unidades:plan.unidades.map((u,j)=>i===j?{...u,[clave]:valor}:u)})}
  function etapa(i,j,clave,valor){unidad(i,'etapas',plan.unidades[i].etapas.map((e,k)=>k===j?{...e,[clave]:valor}:e))}
  const estado=actual&&guardados[`Conocimientos|${actual.fila.id}`]
  return <section className="recintos max-w-6xl mx-auto p-4 sm:p-6" aria-label="Recintos y negocios">
    <header className="recintos-intro"><div><p className="text-oro text-xs uppercase tracking-widest">Del lugar al negocio</p><h1 className="font-titulo text-3xl mt-2">Recintos que generan valor.</h1><p className="text-arena mt-2">Borrador para socios · supuestos editables · ninguna etapa aprobada por defecto.</p></div><button className="boton-secundario" onClick={()=>window.print()}>Imprimir borrador</button></header>
    {!validos.length?<p role="status" className="tarjeta p-5 mt-5">No hay un borrador de recintos disponible para esta sesión. El acceso a los datos de negocio conserva los permisos del tablero.</p>:<>
    {!espacioId&&<div className="recintos-kpis"><Kpi nombre="Valor patrimonial modelado" valor={dinero(total.valor)}/><Kpi nombre={`Valor por acción · ${acciones.toLocaleString('es-MX')} acciones`} valor={dinero(total.porAccion)}/><Kpi nombre="Flujo anual antes de deuda e impuestos" valor={dinero(total.flujo)}/><Kpi nombre="Inversión inicial modelada" valor={dinero(total.inversion)}/></div>}
    <p className="recintos-nota">Valor de estudio = inmueble + operación después de renta imputada + regalías netas − deuda. No es precio de colocación ni avalúo. La renta imputada evita valorar dos veces el uso del inmueble; no se descuenta del flujo consolidado del propietario-operador.</p>
    <div className="recintos-barra"><div className="flex flex-wrap gap-2" aria-label="Escenario del borrador">{[['prudente','Prudente'],['base','Base'],['impulso','Impulso']].map(([v,n])=><button className={escenario===v?'boton-primario':'boton-secundario'} key={v} onClick={()=>setEscenario(v)} aria-pressed={escenario===v}>{n}</button>)}</div><span className="text-xs text-arena">{escenario==='base'?'Valores editables del borrador':escenario==='prudente'?'Demanda −20% · precios −10% · costos +10%':'Demanda +10% (máx. 100%) · precios +10% · costos +5%'}</span></div>
    {(total.errores.length>0||errores.length>0)&&<p role="alert" className="text-ladrillo">Revisar: {[...total.errores,...errores].join(' · ')}. No se muestra una suma parcial como total.</p>}
    {!espacioId&&<div className="recintos-selector" aria-label="Seleccionar recinto">{validos.map((x,i)=>{const e=datos.Espacios.find(e=>e.id===x.fila.espacio_id);const a=ARTISTAS_SONORA.find(a=>a.nombre===planes[i].artista);return <button key={x.fila.id} className={`tarjeta recintos-chip ${idx===i?'elegido':''}`} onClick={()=>setSeleccion(x.fila.espacio_id)} aria-pressed={idx===i}>{a&&<img src={`${BASE}caras/${a.foto}`} alt={a.nombre}/>}<span><small>Recinto {i+1} · hipótesis</small><strong>{e?.nombre||x.fila.espacio_id}</strong><small>{planes[i].unidades.length} unidades de negocio</small></span></button>})}</div>}
    {plan&&<article className="recintos-detalle"><div className="recintos-barra"><div><h2 className="font-titulo text-2xl">{espacio?.nombre}</h2><p className="text-arena text-sm">{plan.concepto}</p></div><span role="status" className="text-sm text-arena">{modo==='demo'?'Simulación temporal':estado==='ok'?'Guardado en el tablero':estado==='error'?<button onClick={()=>reintentarGuardado?.('Conocimientos',actual.fila.id)}>Error al guardar · Reintentar</button>:estado?'Guardando…':'Borrador guardado · pendiente de socios'}</span></div>
    <p className="recintos-nota">{plan.fuente} · {plan.ubicacion}</p>
    <div className="recintos-kpis"><Kpi nombre="Valor del recinto después de deuda" valor={dinero(resultado?.valor)}/><Kpi nombre="Contribución a cada acción del conjunto" valor={dinero(acciones>0?resultado?.valor/acciones:null)}/><Kpi nombre="Flujo después de servicio de deuda, antes de impuestos" valor={dinero(resultado?.libre)}/><Kpi nombre="Cobertura de deuda (DSCR)" valor={resultado?.dscr==null?(Number(plan.deuda)>0?'Falta servicio de deuda':'Sin deuda modelada'):resultado.dscr.toFixed(2)+'×'}/></div>
    <details className="tarjeta p-4 mt-4"><summary>Inversión, inmueble y deuda del recinto</summary><div className="recintos-campos mt-4">{[['area','Área construida disponible (m²)'],['inversion','Inversión inicial total (MXN)'],['activo','Valor inmueble estabilizado (MXN)'],['deuda','Saldo de deuda (MXN)'],['servicioDeuda','Servicio anual de deuda (MXN)'],['multiplo','Múltiplo operativo (años)'],['multiploRegalias','Múltiplo regalías (años)']].map(([k,n])=><Campo key={k} nombre={n} valor={plan[k]} editable={editable||modo==='demo'} onChange={v=>cambiar({...plan,[k]:v})}/> )}</div><p className="recintos-nota">{plan.baseValor}. Inversión es desembolso; valor es una hipótesis distinta. Recuperación simple antes de deuda e impuestos: {resultado?.recuperacion>0?resultado.recuperacion.toFixed(1)+' años':'no alcanzable con flujo positivo'}.</p></details>
    {plan.unidades.map((u,i)=>{const r=resultado?.unidades?.[i];const artista=ARTISTAS_SONORA.find(a=>a.nombre===u.artista);return <details className="tarjeta recintos-unidad" key={u.id} open={i===0}><summary><span className="recintos-cara">{artista&&<img src={`${BASE}caras/${artista.foto}`} alt={artista.nombre}/>}<span><strong>{u.nombre}</strong><small>{u.modelo} · {u.unidad}</small></span></span><span className="text-oro">{dinero(r?.valor)}<small>valor asignado de la unidad</small></span></summary><div className="recintos-contenido"><p>{u.propuesta}</p><p className="recintos-nota">Identidad musical propuesta: {u.artista} · {artista?.origen}. Referencia creativa; no representa sociedad, respaldo ni contratación confirmada. <a href={artista?.fuente} target="_blank" rel="noreferrer">Origen</a> · <a href={`${BASE}caras/CREDITOS.md`} target="_blank" rel="noreferrer">Créditos de fotografía</a></p><div className="recintos-kpis"><Kpi nombre="Ingreso retenido anual" valor={dinero(r?.ingreso)}/><Kpi nombre="Flujo operativo + regalías netas" valor={dinero(r?.flujo)}/><Kpi nombre="Ocupación de equilibrio tras renta imputada" valor={r?.equilibrio==null?'No calculable':r.equilibrio.toFixed(1)+'%'+(r.equilibrio>100?' · no alcanzable':'')}/></div><p className="recintos-nota">{u.formula}. Los periodos y precios corresponden a la unidad indicada; no suman aforo de pie y butacas.</p><details><summary>Editar supuestos de esta unidad</summary><div className="recintos-campos mt-3">{campos.map(([k,n])=><Campo key={k} nombre={`${u.nombre}: ${n}`} valor={u[k]} editable={editable||modo==='demo'} onChange={v=>unidad(i,k,v)}/>)}</div><p className="recintos-nota">Regalías: bruto × participación del distrito × (1 − gestión). Cero significa no monetizarlas en este escenario. El complemento es ingreso neto retenido, no ventas brutas del concesionario.</p></details><h3 className="font-titulo text-xl mt-5">Decisiones para llevarlo a operación</h3><ol className="recintos-etapas">{u.etapas.map((e,j)=><li key={j}><b>{j+1}. {e.nombre}</b><p>{e.propuesta}</p><p className="recintos-nota">Para cerrar: {e.criterio} · Responsable propuesto: {e.responsable} · {e.plazo}</p><label>Decisión de socios<textarea className="campo mt-1" placeholder="Pendiente de decisión" value={e.decision||''} disabled={!editable&&modo!=='demo'} onChange={ev=>etapa(i,j,'decision',ev.target.value)}/></label><span className="text-xs text-oro">{e.decision?'Decisión registrada para revisión':'Pendiente · no aprobada'}</span></li>)}</ol><p className="recintos-nota">Indicadores: {u.kpis}. Riesgo principal: {u.riesgo}.</p></div></details>})}
    <details className="tarjeta p-4 mt-4"><summary>Conciliación del valor del recinto</summary><p className="recintos-nota">Inmueble {dinero(resultado?.activo)} + operación residual {dinero(resultado?.operativo)} + regalías {dinero(resultado?.regalias)} − deuda {dinero(resultado?.deuda)} = {dinero(resultado?.valor)}. Área de unidades {resultado?.areaAsignada?.toLocaleString('es-MX')} / {plan.area?.toLocaleString('es-MX')} m²; el área común no asignada permanece en el recinto. El valor asignado de cada unidad no es un título de propiedad ni una acción independiente.</p></details>
    </article>}</>}
  </section>
}
function Campo({nombre,valor,onChange,editable}){return <label className="text-xs text-arena">{nombre}<input className="campo mt-1" type="number" min="0" step="any" value={valor??''} disabled={!editable} onChange={e=>onChange(e.target.value===''?'':Number(e.target.value))}/></label>}
function Kpi({nombre,valor}){return <div className="tarjeta p-4"><small className="text-arena">{nombre}</small><strong className="font-titulo block text-xl mt-1">{valor}</strong></div>}
export default function Recintos({espacioId}){const ctx=usarDatos();return <RecintosVista {...ctx} espacioId={espacioId}/>}
